- .github/workflows/release.yml
Replaces https://github.com/jetstack/jsctl/pull/3
> Bump goreleaser/goreleaser-action from 2 to 3

- .goreleaser.yml
Adds a wrap directory in the zip artifact for cleaner scripting and general cleaniness.
I'd also be keen to change the naming convention of the archive names to is '-' separator instead of '_', as that is more convention, or at least matches what we do on [cert-manager](https://github.com/cert-manager/cert-manager/releases). Not a huge deal though.
question: Any particular reason for using `zip` over `tar.gz`?
> Release artifact: wrap directory

- internal/auth/auth.go
- internal/command/auth.go
- internal/command/command.go
- internal/command/operator.go
- internal/command/registry.go
- internal/operator/operator.go
- internal/operator/operator_test.go
- internal/registry/registry.go
- internal/registry/registry_test.go
- internal/subscription/mocks_test.go
- internal/subscription/subscription.go
- internal/subscription/subscription_test.go
Fixes https://github.com/jetstack/jsctl/issues/9
We are building an improved installation flow where users are guided through installing the operator using in the Jetstack Secure UI. These changes are to make that easier by:
* Not requiring users to have registry credentials downloaded to install the operator
* Making flag names for registry credentials distinct from JSCP credential files
* Allowing users to see who is logged in and what their current organisation is with `jsctl auth status`
> Implement automatic registry credential fetching & auth status command

- internal/command/auth.go
This allows users to copy the URL if they are using a browser other than the default
```
$ go run main.go auth login
Opening browser to: https://auth.jetstack.io/authorize...
You will be taken to your browser for authentication
```
> Print login URL to terminal

- go.mod
- go.sum
- internal/command/operator.go
- internal/operator/operator.go
- internal/operator/operator_test.go
This commit implements a command that allows the configured approverPolicy to be set using a flag based on the tier.
```
$ go run main.go operator installations apply --stdout --tier=enterprise-plus | grep approver
approverPolicyEnterprise: {}
$ go run main.go operator installations apply --stdout --tier=enterprise | grep approver
approverPolicy: {}
$ go run main.go operator installations apply --stdout --tier="" | grep approver
approverPolicy: {}
$ go run main.go operator installations apply --stdout | grep approver
approverPolicy: {}
```
Only setting 'enterprise-plus' will enable the `approverPolicyEnterprise` setting.
> Implement tier selection for operator installations apply

- .github/workflows/release.yml
- .goreleaser.yml
This was missed before, release notes were skipped right at the end of the file. This was unlrelated to the goreleaser action as previously expected.
> Automatically generate release notes again

- internal/command/operator.go
- internal/operator/operator.go
- internal/operator/operator_test.go
This PR ensures that any Secrets get created before resources that might be using them, for example, image pull secret for the operator gets created before the operator's deployment.
To test:
1. Create a cluster, authenticate with JSS, create agent
2. Run `jsctl operator deploy --registry-credentials-path <path-to-creds>`
3. Wait for the operator's deployment to become ready
4. Run `kubectl describe deploy js-operator -n jetstack-secure`
5. Observe errors related to image pulling
6. Repeat steps 1 - 4 using code from this PR
7. Observe no errors related to image pulling
Fixes https://github.com/jetstack/js-operator/issues/301
> Fix secrets order

- internal/operator/operator.go
This was missing since it checked for the presence of the path
> Set pull secret for voh when using auto creds

- Makefile
This adds a testing make target
```
$ make test
/Users/charlieegan/.goenv/versions/1.19.0/bin/go test ./...
?       github.com/jetstack/jsctl       [no test files]
ok      github.com/jetstack/jsctl/internal/auth (cached)
?       github.com/jetstack/jsctl/internal/client       [no test files]
ok      github.com/jetstack/jsctl/internal/cluster      (cached)
?       github.com/jetstack/jsctl/internal/command      [no test files]
ok      github.com/jetstack/jsctl/internal/config       (cached)
?       github.com/jetstack/jsctl/internal/docker       [no test files]
ok      github.com/jetstack/jsctl/internal/kubernetes   (cached)
ok      github.com/jetstack/jsctl/internal/operator     (cached)
ok      github.com/jetstack/jsctl/internal/organization (cached)
ok …
```
> Add a test make target

- .goreleaser.yml
- go.mod
- go.sum
- internal/command/command.go
- internal/command/version.go
- main.go
This adds a version command to the CLI.
The output from a dev build on this branch looks like this:
```
$ ./dist/jsctl_darwin_arm64/jsctl version
0.1.7-SNAPSHOT-6691014, commit 6691014cee9f7aeedf0c9ec4984cb84e02ea4bde, built at 2022-10-06T13:18:54Z
```
> Implement a version command

- internal/command/operator.go
- internal/operator/installers/v0.0.1-alpha.13.yaml
- internal/operator/installers/v0.0.1-alpha.16.yaml
- internal/operator/installers/v0.0.1-alpha.17.yaml
This PR:
- ensures that a registry passed by `--registry` flag to `operator deploy` command is also used for cainjector image
- by default pulls cainjector image from JSE GCR, not quay.io (because we want JSE GCR to be the single place where enterprise customers can consume images from)
- adds v0.0.1-alpha.17 version of js-operator
To test this
1. Set up a cluster with agent
2. Run `go run main.go operator deploy --auto-registry-credentials`
3. Observe that cainjector and js-operator deployments become ready and the operator is at version v0.0.1-alpha.17
> Parameterize cainjector image, add latest operator version

- internal/command/auth.go
- internal/command/clusters.go
- internal/command/operator.go
- internal/command/organizations.go
- internal/command/registry.go
- internal/command/users.go
- internal/command/version.go
```bash
$ go run main.go operator deploy versions
Error: accepts 0 arg(s), received 1
Usage:
jsctl operator deploy [flags]
...
```
> Ensure correct number of args are used

- internal/kubernetes/kubernetes.go
Closes https://github.com/jetstack/jsctl/issues/23
When ~/.kube/config did not exist or the cluster had been deleted, jsctl would panic like this:
```
$ go run main.go operator deploy
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105c214f0]
goroutine 1 [running]:
k8s.io/client-go/kubernetes.NewForConfig(0x105cf3d2b?)
/Users/charlieegan/go/pkg/mod/k8s.io/client-go@v0.25.2/kubernetes/clientset.go:422 +0x20
github.com/jetstack/jsctl/internal/kubernetes.NewKubeConfigApplier({0x105cf3d2b?, 0x30?})
/Users/charlieegan/Code/jsctl/internal/kubernetes/kubernetes.go:87 +0x2c
github.com/jetstack/jsctl/internal/command.operatorDeploy.func2({0x10621da80, 0x140004a28d0}, {0x1060665e0?, 0x106c57000?, 0x105fc05a0?}) …
```
> Fix panic when missing kubeconfig or cluster

- internal/command/operator.go
Before:
```
$ go run main.go operator deploy --version=foo
operator version foo does not exist
exit status 1
```
After:
```
$ jsctl operator versions
v0.0.1-alpha.17
$ go run main.go operator deploy --version=foo
operator version foo is unknown or not supported by this version of jsctl. Run 'jsctl operator versions' to see the supported operator versions.
exit status 1
```
> Prompt user to check supported versions if unknown

- .goreleaser.yml
This command should generate a valid archive name.
```
echo "jsctl-$VERSION-$(uname -s)-$(uname -m)" | tr '[:upper:]' '[:lower:]'
```
> Replace amd64 with x86_64 for uname -m URL generation

- internal/command/operator.go
`jsctl operator installations apply` command is currently broken as it expects an argument that it doesn't need
```
irbe@jsctl$ jsctl operator installations apply
Error: accepts 1 arg(s), received 0
```
Signed-off-by: irbekrm <irbekrm@gmail.com>
> Fix number of args for operator installations apply

- .goreleaser.yml
This avoids publishing an incomplete release if the build fails.
> Make releases drafts

- internal/auth/auth.go
- internal/command/auth.go
Fixes https://github.com/jetstack/jsctl/issues/50.
Test this with:
```
go run main.go auth login --disconnected
```
> Implement a disconnected login flow

- internal/command/clusters.go
- internal/command/clusters/connect.go
- internal/command/clusters/delete.go
- internal/command/clusters/list.go
- internal/command/clusters/status.go
- internal/command/clusters/view.go
These values are set after they're passed down to the dependent commands. This pr fixes the issue by passing pointers.
This bug can be seen in main by running clusters connect --stdout
> Fix bug in global flag dependency injection

- docs/reference/jsctl_experimental_clusters.md
- docs/reference/jsctl_experimental_clusters_backup.md
- go.mod
- go.sum
- internal/command/clusters.go
- internal/command/clusters/backup.go
- internal/command/clusters/cleanup.go
- internal/command/experimental.go
- internal/kubernetes/backup/backup.go
- internal/kubernetes/backup/backup_test.go
- internal/kubernetes/backup/fixtures/awspcaissuer-list.json
- internal/kubernetes/backup/fixtures/backup.json
- internal/kubernetes/backup/fixtures/backup.yaml
- internal/kubernetes/backup/fixtures/certificate-list.json
- internal/kubernetes/backup/fixtures/certificate-request-policy-list.json
- internal/kubernetes/backup/fixtures/cluster-issuer-list.json
- internal/kubernetes/backup/fixtures/crd-list-unsupported.json
- internal/kubernetes/backup/fixtures/crd-list.json
- internal/kubernetes/backup/fixtures/googlecasissuer-list.json
- internal/kubernetes/backup/fixtures/issuer-list.json
- internal/kubernetes/clients/clients.go
- internal/kubernetes/clients/generic.go
- internal/kubernetes/clients/generic_test.go
- internal/kubernetes/clients/issuers.go
- internal/kubernetes/clients/issuers_test.go
This implements a command to generate a cluster back up from the state in the K8S API.
Example output can be found in [internal/kubernetes/backup/fixtures/backup.yaml](https://github.com/jetstack/jsctl/blob/629b1a930c5bc9a4a36f2c53e5a70ae3c40c07a5/internal/kubernetes/backup/fixtures/backup.yaml), status and createdTime values come from the k8s yaml generation. These can be removed with a further round of redaction if we'd like.
> Implement `jsctl  cluster backup` command

- .goreleaser.yml
- install.ps1
- install.sh
This is how we recommend the user installs jsctl currently:
```
$ VERSION="0.1.15"
$ ASSET_REF="jsctl-$VERSION-$(uname -s)-$(uname -m)"
$ ARCHIVE="$ASSET_REF.tar.gz"
$ curl -LO https://github.com/jetstack/jsctl/releases/download/v$VERSION/$ARCHIVE
$ tar -zxvf $ARCHIVE
$ sudo mv ./$ASSET_REF/jsctl /usr/local/bin/jsctl
```
This does not work for me since `uname -s` returns `Linux` instead of `linux` and that causes the sudo mv command to fail.
In https://github.com/jetstack/jsctl/issues/51 we were saying not to create a one-line install script, however I'm convinced that the advantages (simple & easy-to-use) outweigh the disadvantages (potentially insecure -> which is a moot point since the script is used to download and run our binary on the machine).
I renamed the release artefacts such …
> Add script to install the latest version of jsctl

- install.ps1
- install.sh
I made an error and used the wrong target name in the scripts. (ARCH-OS instead of OS-ARCH)
> Fix wrong asset target name in install script

- internal/kubernetes/backup/backup.go
- internal/kubernetes/status/status.go
This fixes a typo where the wrong API group was being used in a command that lists Venafi Enhanced issuers in cluster.
Signed-off-by: irbekrm <irbekrm@gmail.com>
> Fix group for VEI issuers

- internal/command/operator/apply.go
In #70 we added functionality to restore issuers from a backup file.
This broke the jsctl command that can be used to generate operator manifests for cases where issuers backup file is not provided.
To verify the bug run `go run main.go operator installations apply --stdout` from latest master and observe failure:
```
irbe@jsctl$ go run main.go operator installations apply --stdout
error extracting issuers from backup file: failed to open backup file: open : no such file or directory
exit status 1
```
This PR fixes that.
Signed-off-by: irbekrm <irbekrm@gmail.com>
> Ensures that manifest generation still works if issuers backup file not provided

- internal/cluster/templates/agent.yaml
In https://github.com/jetstack/jsctl/pull/79, the `agent.yaml` configuration for reporting the VenafiIssuer and VenafiClusterIssuer types was added, but an `s` was missing. Because of that, the agent would fail with the following messages:
```
2023/02/06 14:50:45 server missing resource for datagatherer of "jetstack.io/v1alpha1, Resource=venaficlusterissuer"
W0206 14:50:46.292946  530468 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *unstructured.Unstructured: the server could not find the requested resource
2023/02/06 14:50:46 server missing resource for datagatherer of "jetstack.io/v1alpha1, Resource=venafiissuer"
W0206 14:51:06.172629  530468 reflector.go:424] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list …
```
> venafiissuer and venaficlusterissuer were missing an "s"

- internal/kubernetes/clients/clients.go
- internal/kubernetes/clients/issuers.go
- internal/kubernetes/restore/restore.go
- internal/kubernetes/restore/restore_test.go
- internal/kubernetes/status/status.go
- internal/operator/operator.go
- internal/operator/operator_test.go
- internal/venafi/venafi.go
- internal/venafi/venafi_test.go
I'm trying to reduce the number of unrelated changes in https://github.com/jetstack/jsctl/pull/71 by splitting the PR into multiple smaller PRs.
This PR just "renames the 'v1certmanager' import to 'cmapi'"
> Rename 'v1certmanager' import to 'cmapi'

- internal/kubernetes/clients/clients.go
- internal/kubernetes/clients/fake.go
- internal/kubernetes/clients/generic.go
- internal/kubernetes/clients/installation.go
- internal/kubernetes/clients/issuers.go
I'm trying to reduce the number of unrelated changes in https://github.com/jetstack/jsctl/pull/71 by splitting the PR into multiple smaller PRs.
This PR adds a fake client for to the generic Kubernetes client.
> Add Fake client for generic Kubernetes client

- internal/cluster/cluster.go
- internal/command/experimental.go
I'm trying to reduce the number of unrelated changes in https://github.com/jetstack/jsctl/pull/71 by splitting the PR into multiple smaller PRs.
This PR adds `x` as an alias for `experimental` (source: https://github.com/jetstack/jsctl/pull/71/commits/b413db3ad91015f29d9bcb80251a4e767ccc8cd1)
> Add x as alias for experimental

- internal/kubernetes/status/components/aws_pca_issuer.go
- internal/kubernetes/status/components/cert_discovery_venafi.go
- internal/kubernetes/status/components/cert_manager.go
- internal/kubernetes/status/components/cert_manager_approver_policy.go
- internal/kubernetes/status/components/cert_manager_approver_policy_enterprise.go
- internal/kubernetes/status/components/cert_manager_csi_driver.go
- internal/kubernetes/status/components/cert_manager_csi_driver_spiffe.go
- internal/kubernetes/status/components/cert_manager_istio_csr.go
- internal/kubernetes/status/components/cert_manager_trust_manager.go
- internal/kubernetes/status/components/google_cas_issuer.go
- internal/kubernetes/status/components/isolated_issuer.go
- internal/kubernetes/status/components/jetstack_secure_agent.go
- internal/kubernetes/status/components/jetstack_secure_operator.go
- internal/kubernetes/status/components/kms_issuer.go
- internal/kubernetes/status/components/origin_ca_issuer.go
- internal/kubernetes/status/components/small_step_issuer.go
- internal/kubernetes/status/components/venafi_enhanced_issuer.go
- internal/kubernetes/status/components/venafi_oauth_helper.go
We want to prevent matching images that have common prefixes:
- "cert-manager-csi-driver"
- "cert-manager-csi-driver-spiffe"
- "cert-manager-csi-driver-spiffe-approver"
This PR solves this issue by matching the `:` in the image too, so we can be sure no unwanted suffix exists.
> Prevent incorrectly matching images

- go.mod
- internal/kubernetes/clients/generic_test.go
- internal/kubernetes/status/status.go
- added missing `require.NoError(t, err)`
- explicitly specify `APIPath: "/apis/"` where missing
- specify `APIPath: "/api/"` for some clients that incorrectly did not have this specified
> Add APIPath where missing/ wrong and fix issues in tests

- docs/reference/jsctl_clusters.md
- docs/reference/jsctl_clusters_uninstall.md
- docs/reference/jsctl_clusters_uninstall_verify.md
- docs/reference/jsctl_experimental_clusters_uninstall.md
- docs/reference/jsctl_experimental_clusters_uninstall_verify.md
- internal/command/clusters.go
- internal/command/clusters/uninstall.go
- internal/command/clusters/uninstall_test.go
- internal/command/experimental.go
This PR is part of working on the flow defined in https://docs.google.com/document/d/1AxUss0piE9gb_r31_jBS6mv7zWALDqI0ZIfBUiJj3p0/edit?usp=sharing
Example output in a cluster that has cert-manager-csi-driver, cert-manager-csi-driver-spiffe, cert-manager-istio-csr, a Secret with Certificate owner ref, a Certificate that will be renewed and will expire soon:
```
irbe@jsctl$ go run main.go x clusters uninstall verify
Running checks against cluster Secrets:
* Checking that issued certificates are safe from garbage collection...
Running checks against cluster Certificates:
* Checking for upcoming renewals
* Checking for upcoming expiries
* Checking for currently failing issuances
* Checking for unready Certificates
Running checks against cert-manager integrations installed in cluster:
* …
```
> Implement a simple pre-uninstall check command

- install.ps1
- install.sh
If `jsctl` is found in a location that differs from the location that we want to install to, stop and explain in an error message.
NOTE: If a binary is found at the install location, we just continue and overwrite the binary.
> Throw error if jsctl was already installed at another location

- docs/reference/jsctl_auth_login.md
- internal/command/auth/login.go
This automation removes one step (running "jsctl config set organization [name]") from the getting started flow.
> Automatically select organisation if there is only one connected to the account

- install.sh
> Fix wrong shell profile in install script message

- internal/cluster/templates/agent.yaml
Updates agent installation to version v0.1.39: https://github.com/jetstack/jetstack-secure/releases/tag/v0.1.39
> Update agent version to v0.1.39

- internal/operator/installers/v0.0.1-alpha.24.yaml
See https://github.com/helm/helm/issues/3553 - helm template command does not properly interpolate namespace for namespaced resources
In general, I think we already had a discussion that we want to remove the install commands from this tool and keep it just for helper commands like retrieving creds, verifying cluster status etc
To verify that this works:
- `kind create cluster`
- `kubectl create namespace jetstack-secure`
- Run `go run main.go operator deploy --auto-registry-credentials` from this branch
- Verify that v0.0.1-alpha.24 of the operator got installed in `jetstack-secure`
- Apply an example `Installation` manifest like https://github.com/jetstack/js-operator/blob/main/examples/installation.yaml with lines 18, 19 uncommented, verify that operator installed cert-manager as …
> Ensures that namespace is hardcoded to jetstack-secure

- internal/command/auth/login.go
Fixed initialization of the config object, it was causing nil pointer dereference on the first run:
```
Opening browser to: https://auth.jetstack.io/authorize?access_type=offline&audience=https%3A%2F%2Fpreflight.jetstack.io%2Fapi%2Fv1&client_id=jmQwDGl86WAevq6K6zZo6hJ4WUvp14yD&redirect_uri=http%3A%2F%2Flocalhost%3A9999%2Foauth%2Fcallback&response_type=code&scope=openid+profile+offline_access&state=2402307c-15ab-425b-a2fb-712b5037edf9
You will be taken to your browser for authentication
Login succeeded
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x100981ac0]
goroutine 1 [running]:
github.com/jetstack/jsctl/internal/command/auth.Login.func1({0x1017b7ca0, 0x14000189980}, {0x1017a0160?, 0x14000184f40?, …
```
> [VC-24828] Fixed initialization of the config object

- README.md
3 of the people in this section are no longer with Jetstack/Venafi - and two were listed as maintainers despite having left.
I've changed that section to thank them for their contributions without implying they're maintainers. I intend to follow up with other documentation changes in a future PR, but this PR seems self-contained and good to go!
> Update attributions section
